name: Python CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # ✅ GitHub-hosted Ubuntu

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      # Step 4: Run script
      - name: Run Python script
        run: python script.py  # ✅ assumes script.py is in repo root
